### ISSUE TITLE
Attribute ValidateObject is not exposed

### ISSUE THREAD

**Issue by softmixt** [hydrostack/hydro#106]
Hi I have a issue on using ValidateObject/ValidateCollection validator it looks like is not exposed to outside usage.
Doc Info : https://usehydro.dev/features/form-validation.html
![image](https://github.com/user-attachments/assets/747607e7-5726-462b-8533-8794a55a8030)
![image](https://github.com/user-attachments/assets/49f027bf-4e1e-4ba9-80a9-61b777bf45de)

I see it here https://github.com/hydrostack/hydro/blob/main/src/Validation/ValidateObjectAttribute.cs

Version used: 0.16.2

**Comment by ps-carvalho** [comment]
Just eliminating the obvious but you not missing an import here correct ?

**Comment by softmixt** [comment]
Don't know actually I've just imported Hydro and tried to inport Hydro.Validations

![image](https://github.com/user-attachments/assets/dbd8cc91-3c4b-4d38-b7d5-cffa07618e38)

**Comment by kjeske** [comment]
That change hasn't been yet released. Accidentally the docs have been updated by the github action, my bad. But very soon I will release version v1.0 😄 "Soon" is just a few days. Exciting changes coming, including rendering components like:

```razor
<my-component name="My name" />
```

Instead of
```razor
<hydro name="MyComponent" params="@(new { Name = "My name" })" />
```

For the time being you can temporarily copy the code for [ValidateObject](https://github.com/hydrostack/hydro/blob/main/src/Validation/ValidateObjectAttribute.cs) and [ValidateCollection](https://github.com/hydrostack/hydro/blob/main/src/Validation/ValidateCollectionAttribute.cs) if you want to move further.

**Comment by softmixt** [comment]
Awesome, great news , thanks
