### ISSUE TITLE
Integrating with  orchardcore framework 

### ISSUE THREAD

**Issue by giannik** [hydrostack/hydro#23]
Interesting project. 
Im looking into this project for integrating with an orchardcore module to acheive a similar effect as done with https://github.com/hydrostack/hydro-sales.
So basically the core logic is embedded in a hydro component , based on the docs, that is then rendered on a .cshtml page in razor. 
Correct ?
Thinking out loud  here . OrchardCore uses the concept of shapes which is similar to a view component or hydro component. 
Im wondering if hydro components and shapes could somehow be integrated to acheive the same effect as the  hydro sales app  within an existing orchardcore module. 
Any thoughts ?

**Comment by kjeske** [comment]
Hi!

> Interesting project.

Thanks!

> Im wondering if hydro components and shapes could somehow be integrated

I don't have experience in using OrchardCore, but since it's using Razor Pages and ASP.NET Core, I would assume it's possible to plug-in Hydro the same way as in a regular Razor Pages app. You can then render Hydro components as stated in the docs, by using `<hydro name="..." />`. But I don't know if this is the level of integration that would be enough or you meant something even deeper?

**Comment by giannik** [comment]
Thank you.
I will run some experiments and see how it integrates.
