### ISSUE TITLE
Partial loading replaces whole Body instead of RenderBody() location

### ISSUE THREAD

**Issue by taublast** [hydrostack/hydro#77]
As title, would love ajax-loaded content to replace an appropriate location instead of the whole body.  
Happens for component updates and `Location` calls.

This makes it impossible to have `_Layout=null` for ajax-calls to achieve faster rendering.

Solved in my fork, will make a PR.

**Comment by hanxiao123** [comment]
Agree very much! 
Expecting!

**Comment by kjeske** [comment]
The only issue I see with current code is when you go back in history. In your changes I see:
```js
window.addEventListener('popstate', async function () {
  await loadPageContent(window.location.href, findLocationTarget(), false);
});

function findLocationTarget() {
  let hydro = document.querySelector('#hydro-location');
  if (hydro) {
      return `#hydro-location`;        
  }
  return `body`;
}
```
But if a user chooses another target in one of the requests, we won't know it, and by default refresh possibly wrong region. That's why the target selector can't be any selector, but it only can be either `#hydro-location` or `body`. I will include these changes in a new PR.

**Comment by kjeske** [comment]
Actually I think the target selector should be specified by the target page:

```razor
@{
  if (HttpContext.IsHydro())
  {
    Layout = null;
    this.HydroTarget("#main");
  }
}
```

It makes sense, since the target page "knows" the best what element can be replaced in case of Hydro request.
