### ISSUE TITLE
How to get the return value of executeJS?

### ISSUE THREAD

**Issue by hanxiao123** [hydrostack/hydro#91]
I just need C# get the value from client like 
await var clientValu=await ExecuteJs("myfunwithval()");
is it possible?

**Comment by kjeske** [comment]
If you want to pass the result of `myfunwithval()` to your action, you have to call your action with it as a parameter ([docs](https://usehydro.dev/features/actions.html#javascript-expression-as-a-parameter)).

```c#
public class Content : HydroComponent
{
    public void Update(string value)
    {
        // ...
    }
}
```

```razor
@model Content

<div>
  <button hydro-on:click="@(() => Model.Update(Param.JS("myfunwithval()")))">
    Update content
  </button>
</div>
```

By default it passes the value as a string, but when you have another type, you need to specify that explicitly:

```c#
public class Content : HydroComponent
{
    public void Update(int value)
    {
        // ...
    }
}
```

```razor
@model Content

<div>
  <button hydro-on:click="@(() => Model.Update(Param.JS<int>("myfunwithval()")))">
    Update content
  </button>
</div>
```

If you use it a lot in your view, you can add `@using static Hydro.Param`, so your call will be a bit simplified:
```razor
@using static Hydro.Param
@model Content

<div>
  <button hydro-on:click="@(() => Model.Update(JS("myfunwithval()")))">
    Update content
  </button>
</div>
```

**Comment by kjeske** [comment]
In other words, in an action you can't get the result of your ExecuteJs call, because it will be executed later, when the whole response arrives to the client. So the only way to get values from the JS calls is to pass it to your action with parameters.

**Comment by hanxiao123** [comment]
If I just want to read the value returned by the script when the page initializes, rather than actively triggering value retrieval with a click or other event, how should I do?

**Comment by kjeske** [comment]
When you access your application, the whole page is rendered by the server and the final HTML is generated. At this point no JavaScript is executed, since it's pure Razor page. If you want to get some value from JavaScript expression at load, you would have to make additional call. Example:

```razor
@model MyComponent 

<div hydro-on:load.window="@(() => Model.Init(Param.JS("myfunwithval()")))">

</div>
```

In this way, Hydro will call your Init action with result of your JS call once window is loaded.

If you want to call your action once the component initializes (either page load, or just it showed on the page) you can use the following technique with some usage of alpine (`x-init`):

```razor
@model MyComponent 

<div class="flex gap-6" hydro-on:init="@(() => Model.Init())" x-init="$nextTick(() => $dispatch('init'))">

</div>
```

I will probably add this part `x-init="$nextTick(() => $dispatch('init'))"` to Hydro core, so it's not needed to write it.

What kind of value you want to pass to your component?

**Comment by hanxiao123** [comment]
` <div>
 <div class="flex gap-6" hydro-on:init="@(() => Model.Init(Param.JS<long>("abc()")))" x-init="$nextTick(() => $dispatch('init'))">
  </div>
  <script  >
      function abc() {
          return 1111;
      }
  </script>
</div>
//test.cshtm.cs:
public async Task Init(long v)
 {

 }
`

Model.Init can't run.
public async Task Init(int v) or public async Task Init(string v) 
is ok.

**Comment by kjeske** [comment]
Ok, great. Will look into that `long` type. I will close the issue for now and create another one for introducing the `init` functionality.
