### ISSUE TITLE
hydro-on tag helper does not work and not showing intellisense. 

### ISSUE THREAD

**Issue by gbthakkar** [hydrostack/hydro#98]
I am trying to follow the example from document "Getting Started".
And observed for the code below 
<button hydro-on:click="@(()=> Model.Add())">
    Add
</button>

that when I type "hydro" I do not see the intellisense for hydro-on:click

Please help.

Thank you.

**Comment by kjeske** [comment]
Hi! Due to some limitations in IDEs, the tag helpers using [DictionaryAttributePrefix ](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.razor.taghelpers.htmlattributenameattribute.dictionaryattributeprefix?view=aspnetcore-8.0) are not suggested. So you would have to write them without intellisense. They follow same convention as x-on directive from alpine js, so you can check the [docs here](https://alpinejs.dev/directives/on). For example, if in alpine you have:

```razor
<input x-on:keyup.shift.enter="..." />
```

in Hydro it will be:
```razor
<input hydro-on:keyup.shift.enter="@(() => Model.SomeAction())" />
```

**Comment by gbthakkar** [comment]
oh, ok. 
Do you think that this will work in future?

**Comment by kjeske** [comment]
Hard to say. Not sure why IDEs are not showing even simple `hydro-on` suggestion at all, since it's a valid tag helper. I would need to raise a ticket.

When it comes to customization of the handler behaviour, for example `hydro-on:keyup.shift.enter`, that i doubt there will be intellisense for. There are many different combinations and there is not way to configure suggestions to it.

**Comment by kjeske** [comment]
Closing for now since currently there is no solution for that, if you have more questions feel free to ask :)
